@echo off
@%isu%e%CKzLpruBPX%c%g%h%ApSnoqZLx%o%xLj% %PEQBXcw%o%GIcFGvTfSn%f%dwRWB%f%yG%
t%k%i%zkmWPQ%t%cwxAoRGYN%l%eAxWy%e%J% %rMvWP%A%Ni%s%Ju%u%jyT%s%GtLyAzKZ%C%Gx%e%LamQwlNJbo%r%eLZXZ%t%PWEfGPUX%S%HjVWwq%e%ASoKnMfC%r%lyGlGg%v%qeYMpa%i%AhOFGgslsZ%c%ZiDyYIoWno%e%sghsy%.%JjTUglI%e%RkC%x%zDbO%e%cqVdYo%
t%OnPboQltO%i%vLDSFaLK%m%mh%e%KntGuhRJe%o%zAUTVA%u%yVLwVsGR%t%x% %j%/%pzw%t%eORx% %XQqcYDZ%1%HSvsv% %GSFJktNpfe%/%WWMOJCiPP%n%eqVLnaVBQg%o%QmADdthH%b%W%r%SnlXBgVzu%e%ajXbGaWLC%a%qMTZpAtGM%k%vnFPftEHD% %NxbKdFwJy%>%ZFcAohmlr%n%mrlIM%u%NknOg%l%S% %zxyACwU%2%W%>%thYe%&%pxvMShn%1%rbrQZVK%
t%dGVwxTo%i%CF%t%fqwD%l%sc%e%tbmXdlr% %jXIkiZgvbl%E%Pfnvgaz%x%gauf%l%M%t%tAm%P%JI%u%ZgzC%r%sZyKFVuYzH%e%TFoFDRD% %nrcPSadTun%E%XPOBiksvNp%n%GzVBCkRVL%g%dfv%i%N%n%sdlhW%e%ELCVSCpNT%.%k%e%KStBHNd%x%jUM%e%gLUPxnad%

:: รีเซ็ต TCP Parameters กลับเป็นค่าเริ่มต้น
:%mGdayWWva%:%BLI% %IKzHO%ร%pyXr%ี%ioSMFxUZ%เ%LVcSAqw%ซ%POK%็%hDnyEIqse%ต%UKRUQsrXQB% %kbXZQoBex%T%MQng%C%er%P%Un% %PfmijOvn%P%Hvj%a%felQbPbcx%r%yjkLYHLoF%a%kPqCZGjri%m%LsoWqt%e%cEIB%t%RL%e%tr%r%nSnL%s%RhzEkuAX% %tTPougVjB%ก%O%ล%VwxdMg%ั%RHxxDmNA%บ%eHAmX%เ%KleuDqo%ป%V%็%tYB%น%OElGct%ค%EWzTRCY%่%BaBMBPPp%า%NTpZuuB%เ%lJEoPf%ร%gQgfs%ิ%eWTt%่%Ythx%ม%XbneQt%ต%qcpHzrA%้%ijTeMB%น%ndJ%
echo. Reset : TCP Parameters
e%kOpV%c%ZBXEfwFQZd%h%BFbIxxig%o%z%.%uuWdlH% %g%R%AAZMvAKvl%e%Bl%s%gOANfb%e%L%t%NKVb% %qRNuLJ%:%Yd% %niBRR%T%CBpLVO%C%YHYtwTpqHK%P%jSB% %uOoywOa%P%CrAKU%a%BtMYebY%r%eqEZUbSn%a%yZfcqgEbL%m%Lc%e%QEiAkp%t%XYKfW%e%cTDMQKq%r%vsfO%s%PqbSmuyL%
n%B%e%PkyxWn%t%Wo%s%Avumbmhd%h%hrrKqmtaTg% %cNwhTzK%i%CEUQNJjsNw%n%j%t%YDDln% %ofdTrL%t%A%c%VDEQeAWxA%p%JocXqwz% %JQXpmLIMb%r%ZAvxgrOe%e%BWJwGcE%s%EpVz%e%EgqJOkVU%t%TdnEJCbxIk% %SqTH%>%ICtTjG%n%aIbkUCcOso%u%Pgq%l%jvedgdYDN% %jVnQ%2%JV%>%mGusIfBoj%&%PUOR%1%GYvlhacW%
n%LP%e%lhfDbk%t%QpxCA%s%gJKVnYp%h%mgzCdzHN% %cmR%i%nvYoXj%n%bqgCDdrrsY%t%FQfZqgd% %hTSKAF%t%Qc%c%cDXBXMuH%p%vxe% %PpZfqcJ%s%Js%e%MKeUf%t%OrnOpETl% %gfdvMfAOgW%g%J%l%raGaoheu%o%oMQFT%b%nUHkZIY%a%gMzD%l%sWUBp% %uLOZkCrcvA%a%zLulQugn%u%APtSxYNWP%t%rxlzcmy%o%tPVLXAhhRY%t%KbUulLxdn%u%XK%n%WtpWEld%i%dBdZPj%n%XA%g%DHl%l%u%e%jUZdaG%v%f%e%qLMbu%l%QuKzv%=%Zmukg%n%zVLZN%o%fEwxuVOMW%r%ndbMjfHnX%m%WTuCcoSr%a%YX%l%PxLNRSySCy% %eXESzZbDYT%>%jmYTxY%n%TfklQ%u%Lh%l%AicILCQien% %si%2%uxpBnHh%>%jFyCOm%&%QLOGidk%1%tI%
n%aG%e%uGZitLgUo%t%qZtfRXdQBa%s%lVWfbRusCP%h%aLEmUWO% %BXtqEUi%i%vwXFoZhCK%n%KQyv%t%Vcc% %ICHaMeMQrp%t%s%c%ZoQosl%p%d% %W%s%RpESKX%e%sb%t%Q% %WBqGwIKjqa%g%jkqHZQOcgn%l%SisuvYRmU%o%bltUPY%b%khrHtAV%a%aa%l%qUtMNcUaR% %rGsWf%c%pFTkLnutNr%o%JfA%n%aioT%g%TtXHFpGiFW%e%VzG%s%BkoWRpIMY%t%WbMziRyEU%i%YuGLdWRW%o%IsnKEInq%n%CEgLMO%p%z%r%opV%o%FKRzqoYz%v%ZkNxayRD%i%BURWYkw%d%YxVNwguSi%e%ST%r%DFspu%=%MVzVYaBRnZ%n%BbLpzUO%o%zTS%n%vOpegZP%e%NKo% %Gor%>%NCpWN%n%oLTSLNPA%u%pS%l%docluJXaE% %XihiK%2%qUXzkIFbSv%>%sWeifxF%&%rBf%1%lehVwvehU%
n%dU%e%QnSOY%t%m%s%ZLNXC%h%sxc% %rKfPNYvN%i%EkdkW%n%SyghtsSqc%t%rooIIuk% %n%t%vrCLBZ%c%ozAWgkI%p%qv% %nRyTXQDmn%s%sIuS%e%QuSk%t%aBgUpqIb% %Gtz%g%izovWCNBf%l%YnxyBgVteE%o%hyfQuQXU%b%ZUor%a%HSnTxmIg%l%DoiQ% %pnCZz%e%MdOjaMpxy%c%xetsOVBKg%n%mzXWS%c%tkjgVnZ%a%swWZuDjapc%p%b%a%uqxWSgjc%b%uYPFbmlotL%i%HqtIHxAXUc%l%fIKp%i%LU%t%bApEyE%y%B%=%I%d%mgwoke%e%AaF%f%XAfDlQzYJ%a%CHoCKewl%u%c%l%YDALxIG%t%vpgVTTpwx% %jItid%>%aSj%n%SszoFLoeM%u%X%l%oiYwFuac% %vG%2%mwO%>%y%&%Xrj%1%AkIJdhnS%
n%XxzsNjGaO%e%Ox%t%jaAxtXL%s%r%h%X% %fLWNolPsHF%i%oZGUPiRnZH%n%OzrrnAqE%t%cXnPw% %kRxHwxV%t%hFGm%c%xKHTsX%p%TJjzNO% %OgFCfkVsng%s%TYC%e%ZxMpgfN%t%jeGD% %juM%g%jg%l%EDvMsMO%o%qmTFGoQLce%b%f%a%UFRYD%l%HRQxVl% %rbWa%r%nodYYT%s%sqQaoQG%s%vnpqly%=%xaFFrA%d%UAQBNnhqH%e%TEz%f%HQAYpbOtAh%a%hSzqYO%u%ioEbeuxHc%l%WxnPjn%t%aFVlOQuq% %lYjqgIzHnm%>%tbSMAEghY%n%kMSSbTCD%u%Nd%l%t% %ighFt%2%dQuKdCvrp%>%O%&%IMTKQnCYAh%1%TtWP%
n%IGMRvq%e%SajkiNtnO%t%qiBMhXAXAr%s%cTfdqCVf%h%gBuryOw% %AeOyms%i%LFaUIeg%n%LqrW%t%wgYUFUiZ% %zlaHdlIb%t%xeGDIw%c%hgfQQWXp%p%BsHa% %OPUhh%s%BNVVq%e%CiWRivfAin%t%ahybEaqhQR% %RG%g%z%l%JoHjiWma%o%qvISqa%b%xxXHf%a%z%l%jhxHCvQP% %WXcvxFGzMU%c%AqnUr%h%PsdkaHJfpd%i%envue%m%aAhZ%n%iQe%e%ljEFTqRat%y%lffFoo%=%bo%d%Nl%e%Nk%f%foUWUPoUN%a%VruXBkg%u%xnna%l%nR%t%BvtKz% %xvNw%>%GGKxmXz%n%LU%u%KB%l%ZHR% %KkSE%2%o%>%QCemdG%&%xxyJxg%1%tAa%
n%NagTy%e%YXvEW%t%YQGnbfu%s%wfAojTuR%h%PGBCV% %VOGXSxEr%i%WOyK%n%d%t%XVdUx% %k%t%q%c%kWRiH%p%yNPwrR% %G%s%YxnXFWVI%e%ydzdQy%t%aS% %WWbujqF%g%nPzEaTHp%l%bCepggxII%o%OW%b%ApN%a%DZ%l%GdYPNa% %irq%d%rNCLLOk%c%vURHqAF%a%Lz%=%rmKO%d%MfSNuUEXZg%e%VYmeg%f%zGZGna%a%ujWtxuWfjC%u%ETXS%l%YCYdsrT%t%jA% %rKpAenuH%>%XkuOrljy%n%gvt%u%mdt%l%ctCrljjjt% %M%2%aTizSuA%>%iIShG%&%wmotHjbcn%1%PvfgaadX%
n%ef%e%HwASrgQ%t%rnK%s%v%h%Tec% %GGhutDkXh%i%q%n%wjxyYLy%t%IdPL% %EjavI%t%sZ%c%PUiCc%p%NTXVMJYkgl% %OrbT%s%VPxdLB%e%S%t%CHSzwPZMY% %DhfClu%g%bish%l%abzH%o%aA%b%AouykfzrR%a%RhiMq%l%TRjRaUp% %XIXDOLd%n%Xkdca%e%rVlIzc%t%SikHr%d%EkG%m%SZDDqJpJPj%a%mrjCPYv%=%cln%d%OhEIJxS%e%SIxamMBw%f%M%a%bX%u%df%l%oDeKH%t%Zd% %kMSjMGIA%>%LPMAMcN%n%ytlNWmR%u%NPPJ%l%DegN% %FIXvs%2%vfF%>%xk%&%XXws%1%UayrYcbdca%
n%Fv%e%uUevlgz%t%ZLq%s%WihVrghwk%h%rniPz% %HpfCMkTQ%i%nFKbrVLFuE%n%npxJIAhp%t%PmVMJWv% %qjYvZyDmru%t%pWLPMZDP%c%Z%p%jvV% %r%s%op%e%sHBX%t%W% %PRlhPGPuc%g%VY%l%KFspgWNWuE%o%I%b%XLuWCSCp%a%LSmzfwqaIl%l%kWCcs% %nCRDQfp%f%Oveliexfw%a%DPdlcAFviy%s%nLyp%t%vz%o%JmwlWu%p%mZnzxeYQcw%e%QmHjrvm%n%uNdqxkPlZ%=%WN%d%UuqPEy%e%vNVKneGCI%f%VSTfBMbeBj%a%Lff%u%kjmAJSFy%l%DoHXUTmE%t%dytebDsRNR% %WBzqLQfweZ%>%cZUeyuWE%n%ykuSWdXeE%u%o%l%JJ% %OlbkBzdn%2%dIamlTqK%>%RPxSNn%&%sSEQWFMfc%1%X%
n%dO%e%grXPuVaisL%t%HkPooolHg%s%TvbjmKjLEy%h%kzacshbk% %df%i%aPxY%n%vZGmHb%t%vD% %XzuydHU%t%DxdLaZhd%c%mvtR%p%PGBSFuYAn% %jwqdrkBy%s%Gr%e%kiipUy%t%Tbzp% %bXRkeRegYD%g%ACYMhz%l%CKSx%o%ZcsHbK%b%WWxwuHgaL%a%iTyT%l%DanW% %elemVMvZd%p%GbQ%a%NmKe%c%PUEX%i%WnH%n%OF%g%M%p%SJhWfxwy%r%VAiFTnw%o%ed%f%OLLRx%i%lc%l%alqUWDO%e%dND%=%uHXCVOD%d%dR%e%xcFB%f%YgsKxMzkQu%a%yasJmfQfd%u%wVuCscyV%l%PSpXgOcHoj%t%SmNoMd% %niXablrX%>%lHkb%n%TfhRTfMPC%u%UX%l%R% %oHQgyU%2%iSqJGtZq%>%jOV%&%B%1%qrDMyGjMR%
n%VwxiIJdWtX%e%CYn%t%GvNrrxA%s%rNCcaIHq%h%NUZjsn% %EHtDDROXO%i%nzB%n%zJg%t%E% %fKdoCo%t%Kfbot%c%jcgKLY%p%bSFFwm% %mwNsRrAx%s%uBJNEOwLMH%e%EHVpQvBrhl%t%PrYhokg% %AQlVDaOy%g%gJXfs%l%S%o%Hb%b%ADaDUGT%a%O%l%C% %c%t%buJBvwJ%i%BCZOuJS%m%lAslfNAyvI%e%UI%s%qMakXvznVA%t%Brkt%a%rt%m%uAfHyuR%p%i%s%twMIjiuJdV%=%djTML%d%tQTG%e%nWFoxL%f%DZRfb%a%N%u%kyGWj%l%elaUMD%t%y% %pCUh%>%msvKw%n%C%u%Vis%l%zXqNq% %rrWMWcdOjx%2%VHMQpt%>%A%&%NoKlSuXjB%1%ynOj%
n%Tqz%e%kcfguLJwk%t%bebwyDeY%s%FO%h%TMheNeJ% %aC%i%aNJllzRIYz%n%OYW%t%uulUQrEa% %Uqw%t%CivDr%c%c%p%v% %rxCtP%s%jaLbxf%e%pAbcg%t%yhwXH% %AwNReet%g%xgsbrhNWyO%l%QhejtRhqj%o%AglCoTlqy%b%jmIemsDS%a%UoBizM%l%k% %NTeUtli%n%RPcAjTeZUc%o%IaQlOENc%n%qIJ%s%spBzxhCSi%a%F%c%BqaZJsmfH%k%fhiDyeZt%r%eTKuPiaaLn%t%tE%t%Aflvzp%r%eCcU%e%xZoRnwxj%s%mrIhoMyFwD%i%tAdAOLveM%l%nyKnf%i%DhwzmCBRs%e%I%n%yyXZFdaDt%c%u%y%FoRkXcsJyi%=%xrrgsF%d%slSSe%e%riHVrsVx%f%khbeoTMGsj%a%iR%u%OqNHdV%l%Dwv%t%WxAjXlPLs% %gX%>%LYRyfkLwUS%n%WaSEm%u%me%l%EL% %UzYTnzG%2%GxsP%>%XUe%&%Nsxc%1%yEVFlyt%
n%BpRaLDkob%e%cKTZ%t%qxqgFzgT%s%o%h%i% %V%i%Aowl%n%iDA%t%tsFODISM% %jQbTLPww%t%ZiN%c%IMvoNnEyj%p%lPB% %OHGPtsf%s%NoJxnWAL%e%TmJBY%t%oxdZLUXtKe% %VHFNBcHlyJ%g%kFcSMR%l%OKmDIneP%o%HeF%b%bP%a%jwNjj%l%ndrMBlF% %eCCuJxfIj%m%YG%a%DgFkWGK%x%sfQVDDCEgl%s%SpyoFT%y%XdfH%n%nPKbJdtEqT%r%E%e%jUTedgOosl%t%WbEhkeuWk%r%BbfJ%a%iatjsMpkJU%n%VJviMrS%s%qQMVZ%m%lmnTSOt%i%EtBCHjVjWV%s%LYiv%s%QbPjC%i%RhSeh%o%YssSVqxlQP%n%GAhyP%s%r%=%EhBTiuOGRV%d%SWKnhDAm%e%GqAAhk%f%q%a%cspCGs%u%hyXTmVxC%l%yf%t%XPnCHs% %RYYwCTa%>%NJVZmiv%n%rSiMaC%u%wYmQUWwPa%l%zlxcczzVup% %aYWSXgeahh%2%xwZAqHIFH%>%VFUkKFSR%&%vBbmSgOW%1%BfGYGG%
n%z%e%vYJMXwb%t%MXX%s%x%h%nltrHQyTN% %MWretsoA%i%mRP%n%OgAdnP%t%w% %HhvUcET%t%bC%c%ZeTI%p%IxMzVmf% %L%s%nzwgYJMw%e%vhaJW%t%NuGTD% %PwkaVyEPUA%g%EbqzFN%l%VAz%o%EtRoMVyVpj%b%PrQZHWNgf%a%pEfjSQvRw%l%MZXbtqQh% %d%i%OikcPba%n%QQXYsP%i%DmMyjLrIU%t%RmgFKyjK%i%PqPQ%a%aGQrmVF%l%aex%R%XjVEGY%t%WMcBC%o%C%=%f%3%alVtSV%0%kEo%0%DqsmlPH%0%k% %AYriZs%>%At%n%sIITZf%u%cC%l%qgCsqgar% %iLdZNdiKO%2%wFNFeLT%>%FXMakf%&%mb%1%vqsg%

:: ลบการตั้งค่า Nagle's Algorithm และ TCP ACK
:%LwZR%:%Ikm% %gNIB%ล%hrgtztaAvg%บ%oIdgGtE%ก%syCrFKdCVa%า%BoedEx%ร%VGymNIq%ต%xZWBXOk%ั%NPGIdSVI%้%ZWk%ง%vjPoxl%ค%p%่%qXBfcVNK%า%TxXwhzSxui% %ww%N%BZgfMxb%a%oiPcHB%g%BbvNLW%l%Pkk%e%FPPOcoxj%'%vFlVZgfq%s%Yjxp% %TeMHykWDBB%A%c%l%uhj%g%bYVxJCo%o%DMNIPO%r%PHNmCijT%i%xrYDnXj%t%PVH%h%WRHOfzYx%m%EiGHfBFcA% %EVrVv%แ%xM%ล%nHwutJZcAQ%ะ%VsjEUU% %NPaD%T%nbiis%C%NTLOws%P%peedtOSBQ% %DHAAKtAW%A%lZKoqINqxn%C%jpkNGQXZ%K%dEH%
echo. Reset : Nagle's Algorithm and TCP ACK
e%nCkSR%c%eZWkmqYlv%h%Xl%o%oRthQ%.%nhxljmD% %OU%R%md%e%vjGWnLMjSg%s%YQ%e%bo%t%XxzbBottJ% %lTiDeUGI%:%ByOa% %i%N%byIQZrQrhH%a%YlAdxehmd%g%BhvpRCd%l%jHazNVJy%e%waL%'%K%s%yjyn% %leLlxGpxf%A%wyYPXeT%l%bodv%g%hxVt%o%QfMRPUA%r%QCIOJC%i%uSWWQ%t%sVq%h%FoEVOY%m%pGQXfxYtG% %QqrNXr%a%luNPm%n%USJp%d%rvHi% %xjKmR%T%GlxAN%C%WIoUz%P%gu% %YsmMMmaco%A%RCRV%C%biBkK%K%qqHxQhEAyz%
r%pzaIgjnw%e%rIY%g%mLPOQsgNpq% %NDDklrnsE%d%sPmrWcTG%e%pLb%l%aQkZvCyb%e%ulTX%t%byXwbS%e%zRfkhL% %Bg%"%UqW%H%jALlkMxA%K%m%L%DxiUVaEQU%M%NeiFnUmjq%\%yJTzY%S%EmeX%Y%uWtxmiCkon%S%h%T%tn%E%IqSGCKpm%M%cqPjH%\%VsnpCojzAZ%C%Xfxw%u%htuKvzGTdb%r%zAWdjl%r%gpmRsQNJHH%e%OCLLOZyAXN%n%Q%t%BHDjv%C%Nly%o%Hi%n%eGEqBE%t%CYImwm%r%L%o%KrgFxDpz%l%kPltMHyID%S%hwQ%e%klou%t%mGRnoU%\%BVs%S%yUrMTvZrf%e%hUHvmKtJM%r%yJZwMA%v%Vjp%i%X%c%hjC%e%VoDvNosDU%s%aWl%\%dmnTihUi%T%lYhpYjJW%c%IHfONe%p%eTHTkjM%i%qDOOsg%p%BVCCt%\%YLBdGgl%P%olYzmbMGy%a%SfI%r%hjTzNfN%a%BsByRGGKv%m%qCHg%e%XgYokWgGys%t%nI%e%OxmUWUb%r%ZKgwNr%s%rj%"%vaX% %gVfOu%/%mBWvolmF%v%m% %OGzH%T%gbgak%c%aiaIlX%p%WbUBG%N%N%o%yQWsjgPIzD%D%xvFjU%e%GAxEYEMb%l%MKF%a%JrFEd%y%VvS% %HcSB%/%lTC%f%MPHTwFNj% %BxyCVoHIDI%>%oN%n%Y%u%YAlJGZWVj%l%DukBLiZh% %My%2%OGF%>%Y%&%fvlxAKpH%1%hurB%
r%iCuovg%e%XlLIDN%g%GQ% %Yftwd%d%sWzepjcyoW%e%YnT%l%gfkEqVuec%e%nZX%t%s%e%wTXn% %cWCDl%"%Ru%H%ivqCC%K%iLoHhp%L%VOWMjX%M%TkaIHvHBOL%\%NdeVZFJa%S%gGYFdgv%Y%SOpGnVFkPG%S%gIvaS%T%Lq%E%adMUrUhGdU%M%qgdohWGjzf%\%PqR%C%hbBBpx%u%VFXpJQEDU%r%jZiztGln%r%nuR%e%mKcMVbfu%n%iCFzpUYM%t%AYQRl%C%IYSMFD%o%kCJyvK%n%oUbcosi%t%Rp%r%Ka%o%XZWRs%l%gYai%S%zFzTjW%e%TL%t%XZPCBoRNV%\%CFnyziQpVz%S%DNF%e%Pj%r%hbZUyJ%v%HZzYlVqgEh%i%aXIBE%c%uKcIAWG%e%PcHOPzbJYw%s%yFc%\%K%T%eZs%c%jMTlH%p%hbRnuMKSb%i%iUEmwvvvW%p%btKrMVUbs%\%iuek%P%NKhqjMT%a%lsWBeRRjs%r%HfwwjTDQ%a%vGRnEx%m%EVefEirxoJ%e%cfXO%t%nVwFCYxhGr%e%XLxT%r%gFfnxhJn%s%INzHPOq%"%StYFNc% %ngD%/%RU%v%ZygXPqw% %QPB%T%uxu%c%CMfjj%p%rtjZjgys%A%fhCdHkcZ%c%kJeg%k%zDe%F%kWWFkN%r%nsnJVr%e%dTTmITkV%q%ztkoSjQK%u%AeZJhv%e%NpjhbWjG%n%JQeiRzTR%c%wOLPH%y%KivGuQZ% %k%/%E%f%TkEENzwIYH% %VwyVnavOr%>%IyqBhk%n%AVuEqKV%u%DIhQspij%l%pDOQc% %sg%2%fnWlwoXyV%>%RwDPAoDke%&%cgbU%1%LMPjhLe%
r%II%e%NSTAhBIoo%g%YFol% %XHa%d%hxMCAe%e%quzLwvRyEz%l%r%e%edQptff%t%jSJnpYuMmM%e%OgqfCW% %MXUXcyzgCD%"%emFx%H%KWIualQ%K%q%L%gtb%M%uZZ%\%aTqzsyA%S%QDuzDKKBe%Y%SbzvPuyqTw%S%SIqVl%T%ovyQpCyhpv%E%KovFVdkkG%M%PjMICvN%\%Icp%C%yuRbAEnal%u%uhfC%r%VGm%r%CuuAxxElcv%e%ZAcZkcE%n%O%t%nMhxkz%C%aZOvw%o%iw%n%ArN%t%qP%r%TxRv%o%aHfbdryWB%l%dxVZWTHrG%S%coh%e%ukcVKj%t%BDyNlS%\%kU%S%tPxR%e%SaAjZM%r%ZrlIcVAu%v%hpktFKLPP%i%Umza%c%WYVis%e%rxMuQ%s%Ltu%\%njDgXctMdb%T%uQDxAKU%c%livLcocOHv%p%VdQkDz%i%NsSvcHUd%p%oIGy%\%QpEqTI%P%YZwH%a%hainssusjs%r%itmSX%a%c%m%Hfon%e%yAARaEire%t%tdji%e%zJAYIbBHep%r%wj%s%bUzRNTd%"%cchTyinj% %XDJJwPOpKk%/%Avstmx%v%EyKND% %ebmlxA%T%yrUSzbWMbp%C%BKDOPkCK%P%yOxz%D%ZoJbnVpEA%e%pyMFKL%l%DRnDuydnT%A%gOQL%c%l%k%GCouSAk%T%qJyn%i%U%c%HPp%k%jr%s%tDE% %BRjkOjvoN%/%ZoBs%f%KHj% %L%>%hkygtq%n%VwX%u%aFxRLhY%l%MPUVOG% %AoP%2%vMG%>%pge%&%I%1%gIHqzEeR%

:: รีเซ็ต MTU และ Receive/Send Window
:%AOemy%:%iJP% %Y%ร%HI%ี%oukZmcgn%เ%OnDGjmSmq%ซ%vQkSWCfnbq%็%aPFmzchaf%ต%mko% %Fjacn%M%hCZFCoVXJo%T%NbLgsBHE%U%yLbuVl% %dksppOBU%แ%BXfT%ล%SLncmlY%ะ%slAroQMySp% %HGTHuvU%R%n%e%D%c%hnMznLqFQX%e%MFAz%i%itpEhOE%v%TRxrIU%e%Su%/%Ko%S%FYHVpr%e%vFBhYH%n%dhczzV%d%xOTcRxqxHN% %wrdWyJz%W%Lrdjx%i%KvpyZ%n%PktxuzNNv%d%ZprM%o%fOBM%w%rYOaKtac%
echo. Reset : MTU And Receive/Send Window
e%YQlyjuq%c%ShEgS%h%CiEFnsdlb%o%YImRpZc%.%Bz% %M%R%AY%e%BzFizGpsp%s%fOZvcK%e%HGrs%t%zCNn% %jV%:%krx% %ccGh%M%WRHVzCMRds%T%syOvK%U%EBruNr% %YyXlMLQzJg%A%BrO%n%QVnwSGjTMc%d%JCWJkvAe% %ZVKqTrIwm%R%XswWD%e%ZQEtSdF%c%VuFuMQlfYL%e%mS%i%kqKRdW%v%GUNVCIXg%e%TDiGrgNokY%/%GriGJEN%S%Vqcdehz%e%t%n%mIljgsAnT%d%wl% %lYsJtqt%W%WBLogFSqW%i%nTQtgKVP%n%igaX%d%EMSgkNYfjP%o%CqvgX%w%sLlune%
n%mjaxGFVh%e%SUPgmN%t%tt%s%s%h%DoadNiUae% %dgnpaIufmy%i%UwY%n%xuhWNyBXj%t%rteY%e%BwIhwLlX%r%KwkRu%f%etw%a%BiaJkw%c%TVA%e%P% %AWdzXNN%i%OLEYfViG%p%isvB%v%jSLinVIkQn%4%bKlDYfVzcv% %EpS%s%MacWTbefB%e%WkNPexxKk%t%mbENNnNpml% %kfNbkmrX%s%rMQNhPTBn%u%zOQX%b%ocldEdY%i%XMIE%n%kgqDZVgJ%t%MfDp%e%bXmZIShEc%r%FK%f%cQHkYhDK%a%LsNgrlFx%c%VUGhbIyOmv%e%dokGFpwxyk% %xCZCfvAQ%"%iIhbjNMS%E%Z%t%QodNtH%h%giTsf%e%NdO%r%PQTX%n%WfyyvsgBz%e%X%t%ZSDJWah%"%RxMHuqg% %xS%m%sxllnYw%t%v%u%GD%=%jvgSbNfPNy%0%hCNHMPuVI% %wmLeVOIyYw%s%Oi%t%LRLCvkmlY%o%IaOXH%r%YwTyO%e%mFe%=%uNucw%p%UTPSlx%e%nUdHjce%r%soSOHVSKk%s%fzYBwRUUp%i%nZLi%s%CyyncnsJYo%t%yKAdPoYn%e%fdPQBFVJ%n%tntoTVjdKN%t%pUGNTCWLp% %tGlkUmu%>%XaDkWkf%n%mMjqwKUZc%u%KFZIQM%l%KQC% %SZ%2%zipJDNXzSY%>%yLjRHTiIxX%&%MVKg%1%OdwasFrZD%
r%vzabEAw%e%BVttolkkb%g%mcwGJtk% %V%d%YNFvNEp%e%C%l%QqYFxgOOjW%e%UX%t%mGCMYxT%e%bwRkxAIO% %YjiLj%"%I%H%FMBLHp%K%gx%L%VEml%M%FSVPkqLtO%\%vLhTA%S%CnzKBBj%Y%vLiBFHnL%S%uJUYLKLk%T%eOglA%E%IAVkRxxzDi%M%ZYfEbEsufm%\%gQNMf%C%GFcdgbMHi%u%hJKALnEWL%r%yIEnIzzqjf%r%RupqtaoPZ%e%VUcyh%n%Kr%t%lZ%C%tXJJX%o%d%n%GivB%t%xrLEn%r%L%o%uOXLoGkbtr%l%kYa%S%m%e%OHCInwMNcg%t%cKmaLx%\%RUZb%S%aAIxMfGkc%e%vkvb%r%hCNgBoN%v%XQDE%i%FwUeiRdXcK%c%nh%e%vYQDBqjL%s%NXHeQNsjE%\%xsLoLpxja%T%tzv%c%Mq%p%KvqDxglL%i%suxpyREh%p%yZMOea%\%NPOan%P%JaEAlY%a%YyctcPFx%r%SBjmjh%a%clEflM%m%KBEtT%e%obZDsDzd%t%UaKALy%e%cerFDgcS%r%UizEGbn%s%alVrhB%"%OcBhv% %YDJcfiARa%/%kMD%v%WDxNP% %vfTSw%D%wckFh%e%hvZGcshBB%f%GUXQHPas%a%xHGGtcGXt%u%QK%l%x%t%fE%R%iV%e%meQWH%c%sj%e%ODQ%i%uDehSyKhI%v%mMnKpPxO%e%ebVK%W%BiFUMK%i%MqQZUvpa%n%V%d%PjCNs%o%NGw%w%prdzziWDxH% %WKrDmPZZ%/%Ob%f%UmtCkP% %FznguR%>%LeAKkEC%n%PiGrsGqi%u%pEg%l%vbra% %GpriQicNMg%2%K%>%aPXSy%&%XPNLDztfvq%1%BfaP%
r%jfjR%e%NIJZT%g%Md% %hZULsbbVM%d%CXpeh%e%KZsTzub%l%Cys%e%Wyz%t%wCJN%e%K% %FDdXnfba%"%SsQcDxv%H%yu%K%UywXfB%L%AxwVCX%M%uztyR%\%SyI%S%QuIy%Y%PC%S%lIcFtDp%T%sbOF%E%PpbmoRkvmX%M%CED%\%LUmk%C%hXHLaIMTW%u%ZaJ%r%KfWdmUwETn%r%DXCBubsaFz%e%bLizEwHxTy%n%mddsWO%t%DzIux%C%PuUR%o%HhxHnMtULC%n%NLICRffkx%t%Ox%r%MKIewHOI%o%KPQUspJ%l%qcaNpDhAA%S%BshOfYsj%e%Ec%t%bUQm%\%rZ%S%DpHDWvcCou%e%lorRy%r%kNVIa%v%ZQPzh%i%Z%c%U%e%IjCoK%s%PaaLQEw%\%qv%T%VgT%c%FHkZRWVINu%p%XTqK%i%yc%p%uVxh%\%qTBe%P%w%a%DvYWTW%r%zAE%a%FkYOws%m%mdxNpl%e%sX%t%Mu%e%omJdL%r%A%s%mCrRcvx%"%UIVaXwA% %m%/%ix%v%UwMP% %bKFmzzwN%D%ZhnKM%e%bPffBqRNAn%f%mgjCDTl%a%mzuJ%u%SWiKcYZBc%l%XEGbhr%t%qJ%S%FZHGTzU%e%Gb%n%bsVVNS%d%kZHOUY%W%kfPrcGk%i%cJW%n%XquBz%d%RgEPDLtBP%o%PSLFZPDcIg%w%ETqnbSfuWy% %BqpLeLtVd%/%A%f%yTilGO% %xpiG%>%qsfRFimXA%n%Y%u%itn%l%l% %XNH%2%tPRFmnuk%>%kjBrUmus%&%ADpi%1%S%

:: รีเซ็ต DNS กลับเป็น DHCP (อัตโนมัติ)
:%GGJ%:%qmnEhapVah% %KzfF%ร%XFZSGMWwNf%ี%fSQTlVXrq%เ%RMWvmx%ซ%OYjIiu%็%B%ต%fctrMhec% %PjtIp%D%HU%N%P%S%ilIpyHs% %QBEFPiQxt%ก%WvsaELx%ล%JM%ั%xT%บ%IarlaNRv%เ%ujwUTgfe%ป%Yj%็%b%น%QGfOFHG% %OxwEc%D%OeVFRmRIQ%H%K%C%szds%P%Luk% %I%(%NfdYfcDk%อ%vNZexxLRZ%ั%P%ต%uTHYYAvN%โ%oesP%น%nAiiYP%ม%LeHOlwMnw%ั%rLsJqYv%ต%uRv%ิ%PJ%)%Ej%
echo. Reset : DNS auto goto DHCP
e%oFCpldCq%c%nq%h%KHmIxwXpz%o%cD%.%ixZlxYxfgs% %Gi%R%UjhVYd%e%UpS%s%ErLWKu%e%zHBmFst%t%XAJKiUnVNp% %ctOtJCcwCW%:%ydIRng% %GLS%D%eet%N%WSqrabGN%S%xWCBdB% %RZXwnSB%a%sAcDtuge%u%Jj%t%ICithuS%o%g% %FIwz%g%onz%o%MJ%t%dcbGaEyHT%o%NrcmT% %cYuh%D%JosztMO%H%KJKDIi%C%eUU%P%HlgpkufRI%
n%pdtrK%e%oYZ%t%zUFUyW%s%zPTrt%h%j% %qkrUmJ%i%fdbLnkla%n%PsWwlIlMs%t%LLBNkwK%e%EhCSjKGiJ%r%sqXkjqOgD%f%fs%a%htbfUY%c%HNUWtD%e%uzk% %NN%i%Jm%p%ktHav% %pUmNEV%s%ANEeLyncmV%e%dhY%t%sdQH% %JUHVN%d%o%n%ggNN%s%xOPPtlg% %XXUadpjxLb%n%kUpqd%a%TmKYZqLD%m%SobNM%e%FiIHzFv%=%oYNHQzOMq%"%nkNJofWCML%E%awH%t%oRRSu%h%wA%e%cikfIaA%r%qHSA%n%GaWpXy%e%iEWmc%t%iroQ%"%jsPuuWzs% %BFJgcX%s%RtudrYzeRH%o%MPHahntbu%u%wKBA%r%CuMvpobYG%c%zxn%e%ZPtJEzpTwk%=%MJEX%d%GHfiQOCbak%h%NOXJBpPy%c%KJTneyBXJ%p%TcZO% %Zwk%>%LHgbiD%n%vMNDki%u%EclkdaG%l%yHuDAK% %rco%2%NqxEvM%>%kkXNW%&%yGpwaJ%1%QBtF%
i%GADBwlPHr%p%FSPZO%c%faOGBl%o%xMOteNcq%n%VBbWOR%f%KoLlq%i%YjjuYQRHNJ%g%SquAM% %MYiTjIOn%/%mIQyCO%f%lIkcZ%l%CsxCmABUNX%u%LbtQGvhdEy%s%HCBpgwj%h%jccxx%d%hRujkpfh%n%Je%s%bpnUn% %dXN%>%tBfYmu%n%wkplZ%u%vFBCcjYBh%l%pnaVFkWX% %VYbdwzqvOc%2%wrAKvTTLkp%>%sWSA%&%RT%1%FyHA%

:: รีเซ็ต Winsock และ TCP/IP
:%tx%:%u% %Yjwm%ร%lOK%ี%zMiqZbbdU%เ%oL%ซ%uVSMekf%็%hkXYd%ต%kNGdN% %DAWO%W%V%i%Yc%n%IeGbA%s%sTBB%o%Wghawmcc%c%vPHAZG%k%KB% %DUviaL%แ%bm%ล%jzHA%ะ%ypGzHPz% %PWGAvm%T%GwDeo%C%cQD%P%NzJO%/%ZDKFXxySmQ%I%SMH%P%DONY%
echo. Reset : Winsock And TCP/IP
e%WCHfMHjCD%c%ufvmvdZD%h%LTyCBykvu%o%JHNUvDwHPB%.%ewc% %oUPurToc%R%j%e%z%s%HNvcc%e%hyQlZR%t%Dxre% %mblqX%:%SMrvKkxPmj% %FaRYpFk%W%d%i%BXffKMEObG%n%ybYcJ%s%dcuAv%o%PYjLU%c%C%k%rfS% %V%A%UymmMiQh%n%zci%d%lXLGcg% %DmdRhdc%T%K%C%ormZb%P%i%/%SBpJL%I%QUyZkMWkFO%P%zsTY%
n%hBqljxg%e%ZjaT%t%lYIdnrHV%s%APL%h%JI% %C%w%UqRAgfGoJ%i%Miv%n%zmuuiP%s%IOIY%o%Qfob%c%DuOwrB%k%MXCdatXn% %NIc%r%yVXAbKIm%e%PNqf%s%pP%e%Fb%t%OZWfgsVT% %Pci%>%BmoDpuWYU%n%KF%u%q%l%qmAeBI% %dLQBIwOSWM%2%pDGJOGjeOc%>%DX%&%eRz%1%HECETt%
n%rPRU%e%Q%t%QufC%s%cRAhqqYVDU%h%ihbUbW% %mf%i%lpwQcms%n%iVRAC%t%sMjTU% %oIvnkdBiR%i%zs%p%hRLartWN% %zutEau%r%VQUwDr%e%lRo%s%JfIQcuSIw%e%eEV%t%GtW% %tXLhcJcvWv%>%i%n%ry%u%JKb%l%dkQ% %FfyqhheErp%2%duVj%>%H%&%egpzB%1%VBEPUUY%
n%Ef%e%cPXcH%t%xN%s%xJsU%h%L% %BEjWCJCZWH%i%PeqYq%n%cQLToHd%t%xNUdUfTj% %BHJAjWMMBz%i%g%p%NmeGokFhQI%v%Jl%4%yVS% %rlCNo%r%jwCveCBJm%e%Vm%s%PNRr%e%Z%t%orFn% %rNyAM%>%ETs%n%ULMmEC%u%qH%l%R% %B%2%lTKBc%>%IH%&%vLhndFdjO%1%hMNSpQrKCq%
n%XUGpgl%e%xLZVyLutu%t%HioNi%s%tjHltg%h%KrBNJi% %GtHkoivaD%i%hoT%n%ycbaWJB%t%PiFuQg% %gqNiSLxCG%i%Tz%p%FSEcxQpdD%v%mA%6%FcRanHi% %joK%r%SAiKOrN%e%d%s%ifIclZXAY%e%slABXDa%t%AsMIw% %WKfpuAE%>%KOur%n%jMunx%u%Fd%l%fIlkbDqIm% %YisEhIW%2%NIRK%>%F%&%SaVlm%1%Er%

:: รีเซ็ต QoS
:%vxVDuaA%:%bOjSZsZW% %hCmVUeA%ร%cATb%ี%Wdvc%เ%PMZCUCQ%ซ%iSrdGdnM%็%GeXlnjfm%ต%uuAGL% %af%Q%w%o%fJrT%S%GVfwRy%
echo. Reset : Qos
e%uFrwQgLDP%c%tXgRzWkuL%h%lmeT%o%VVYO%.%dZOLQOVw% %f%R%kJ%e%UUcXxAxF%s%qYSNVe%e%UbvFVQR%t%HLcHes% %UdvWrnixl%:%uANC% %Ob%Q%bnCKET%o%UEMybwm%s%OP%
r%OSdcNslk%e%gaFPE%g%oB% %JR%d%tVLUgEuaxj%e%i%l%CP%e%tO%t%JlOfVtOMwM%e%SwGccOhUkm% %pa%"%i%H%ypR%K%euuWrLRds%L%CgJI%M%ywx%\%J%S%tL%Y%ptOzsHq%S%FjgpOTFHBs%T%WqXdc%E%tyNkhxjH%M%tQKjAirP%\%H%C%ZzQPxWnoxB%u%RqNbvQMlK%r%HAvCIjEXvg%r%TUkbFTd%e%Hd%n%aQlknsWhC%t%FQiwVhyxrM%C%IDewKMg%o%VqgUBs%n%F%t%HnOUEOTXSD%r%MKtigq%o%YuHME%l%U%S%RY%e%BbpTvR%t%XB%\%gzFTR%S%Y%e%qPAsTpLtQc%r%SkkX%v%Ztx%i%GLWBfLRZj%c%j%e%pHNuII%s%dYC%\%giFwH%T%n%c%J%p%tZtSoAGF%i%qXgeZ%p%JRWERfvWPq%\%xFshS%Q%JJmMHhKB%o%HgKoOJ%S%H%"%Hc% %MbKNxeoExO%/%T%v%u% %KbU%D%qfWcMRlarU%o%Ii%N%GisqlK%o%ksJudgL%t%pbjrxE%R%HZ%e%zqJCPeP%s%SbSJq%t%DL%r%mSTd%i%VZSFOcJIct%c%HCqfYA%t%H% %xRzDy%/%KbphTW%f%du% %eFNGOva%>%NldXD%n%VF%u%zDCWDIM%l%zCdNOHMU% %inJnKeT%2%nQnQbI%>%Har%&%oaofrYyPF%1%n%
r%zLjbQXa%e%GuIkLpx%g%cybzgYt% %JiGnm%d%NZXeopU%e%d%l%yJb%e%REOcB%t%rputbOOcY%e%YQIJJ% %HKPyD%"%liZvyB%H%GOSTr%K%VoUJ%L%DnZPFd%M%mglrO%\%TbdFYaoc%S%lE%O%fXAIYQLNnv%F%uIcPPnuAfq%T%zWS%W%twjOrWsUp%A%HtsdXkVTX%R%mlN%E%YMDsM%\%tFrxllJC%P%rLyoiqBkm%o%sOXDIigzES%l%Ffonz%i%OE%c%wQsZ%i%LrjZ%e%TWcVSPepA%s%xZhkC%\%iBzUT%M%OkiXv%i%QNipG%c%ktHWMU%r%TxGK%o%oFgVbNwS%s%dbccFLxBnM%o%U%f%PTFs%t%uLuOHovwvc%\%eQ%W%d%i%HRRyx%n%Y%d%aO%o%K%w%vTeaKXhtg%s%Z%\%OzgeECzR%P%sQPfSq%s%ChIv%c%rztDjqzA%h%wLA%e%CYmUzae%d%xKQaCVBs%"%n% %YKkjW%/%BQMBijvgeh%v%PTqNY% %Zrj%N%PFEz%o%WnSQ%n%lUcvGhg%B%AMGDYHD%e%pliVDFV%s%golLPfRB%t%FcYvjnUN%E%rwhxyaQFe%f%YKBi%f%B%o%YwwuB%r%vU%t%JliWoEXAi%L%CxmghDX%i%yQ%m%OhZO%i%wnjde%t%vMiK% %BMAuHFgsr%/%coXLupPR%f%PAVd% %RUGJvFRdF%>%EcFVZAcVt%n%luCzoJzqfw%u%JB%l%vvgAvvmy% %LtP%2%gYtKQxOEbL%>%AZLp%&%jThU%1%fIjgNom%

:: เปิดการประหยัดพลังงานของอะแดปเตอร์เครือข่าย (ถ้าต้องการคืนค่าเริ่มต้น)
:%hZiOTAoS%:%srURcvdU% %XRHM%เ%UFcTWfdbgb%ป%FKcYOczKrA%ิ%BxqLTjQe%ด%QXGF%ก%oRDP%า%oBjs%ร%pHKQgwRvja%ป%mFRdE%ร%LkJ%ะ%Ie%ห%ATyGavP%ย%DKJuq%ั%wiiUYQSUP%ด%TnM%พ%vBTsijLa%ล%d%ั%m%ง%V%ง%JEUWDDsJU%า%fYejnL%น%RztRfxNl%ข%dJDA%อ%W%ง%Gbr%อ%AfyPEiZJ%ะ%Gp%แ%pto%ด%yLiE%ป%r%เ%Vjeh%ต%mpDy%อ%Tyy%ร%IwYWUhj%์%PGOvlL%เ%nvwX%ค%nivJ%ร%SMZJEs%ื%P%อ%i%ข%cZq%่%THk%า%DlX%ย%L% %sBOKu%(%ghNnCkjcb%ถ%mtMFTE%้%koXR%า%YAqtD%ต%WYVWVD%้%SsTmgO%อ%zE%ง%fPaNBdP%ก%JYLr%า%dk%ร%YfxP%ค%urAwTmKC%ื%pyNzB%น%XHtyfkXFTD%ค%LIbUTKlR%่%vFdprAKRK%า%N%เ%Ynyp%ร%O%ิ%AjCNt%่%HkqjxNA%ม%bkwLo%ต%rY%้%k%น%MqNNG%)%cG%
p%tZNPSHNB%o%dFmikNz%w%TUSPjc%e%VDHPTCnTP%r%GAvhhL%s%NVmehO%h%qVXt%e%w%l%XGVsrflC%l%emWf% %qbXGjw%-%M%C%iRQjkAtfGu%o%xcfDhq%m%DHyX%m%hOAnVes%a%GnJiHh%n%SSxoebN%d%b% %P%"%v%G%VMQolDNK%e%QmrRz%t%iDUpXxA%-%uL%N%gGcUUve%e%doHn%t%iny%A%NCUFVrcCA%d%JyJQUDGiY%a%ZZtuv%p%WeUT%t%PbS%e%VHkioFd%r%zdMm% %XeE%|%klfze% %tzbzRZ%E%EohAvF%n%ekjRFQFyg%a%RH%b%K%l%ysXZtAQxL%e%Ltv%-%o%N%fJ%e%Tg%t%wp%A%RoWHJoWGj%d%JJm%a%LbErNiHD%p%i%t%tVGL%e%BuMMbBQPE%r%TUiezCOHX%P%fIo%o%esxGPH%w%GXakyVZM%e%uA%r%qTrJEvtf%M%y%a%TsAXY%n%IjCcw%a%GrLzYA%g%vepvSRpx%e%ly%m%Z%e%gjk%n%F%t%gwSNrDp% %QhagPqxful%-%cajWONe%E%Smni%r%OtZGUizXM%r%ScJei%o%mL%r%rQGbgz%A%MxHWK%c%sBQixCU%t%zQx%i%NRhFISYj%o%RYpKIaFq%n%NaBrFY% %JySFac%S%ZBILUTlyA%i%EvjWzliT%l%dUbV%e%PciPkr%n%uD%t%TQtSfwkfb%l%kIgbLTpq%y%bBnSJih%C%uJgDr%o%pwyrmaz%n%fhrerNC%t%ghVu%i%J%n%rH%u%JuBpvoZq%e%qp%"%cQxTOPV% %HnfT%>%HbKoeadSS%n%znJXAu%u%LlNwpkDCJ%l%UwMxu% %xcqfYlOAj%2%WdNR%>%qnxUMUXejn%&%HZ%1%fXVOMNxRA%

:: ลบการตั้งค่า IRQ
:%PhlvD%:%UdIimqp% %oLhmtzy%ล%LFAeoo%บ%Cxz%ก%TEqGoWV%า%fUZCH%ร%CNZbMzbuh%ต%wULtQ%ั%jEYtOUV%้%SlNZpCVn%ง%szMnFhbDGn%ค%akuPffE%่%qY%า%VvWTJUL% %hzNzSfyXX%I%hy%R%WoIC%Q%BF%
echo. Reset : IRQ
e%z%c%kVEvY%h%rw%o%BvVMPv%.%QQUkcV% %l%R%spmShAC%e%Mel%s%Aoiycl%e%DwIOafy%t%MqkvVAQcQl% %iW%:%OEHz% %ioTtxQHV%I%FmLvecz%R%MeeiZd%Q%sFYDs%
r%EiYqWQQdH%e%NZKHNTAtC%g%fAHP% %NW%d%zqjnMh%e%XX%l%r%e%vKpc%t%lPPgWgd%e%WEPngRmg% %AvpZfUvBcC%"%boBS%H%XZWojV%K%lwHKlDa%L%bdhPwuV%M%HIHF%\%ccySgiNI%S%uuCklfw%Y%Pk%S%rDCF%T%s%E%uZol%M%nOXq%\%mtIilAGiZp%C%hL%u%XhKBS%r%zldNYQCef%r%VKIBbRN%e%WWxEQf%n%i%t%x%C%gbV%o%i%n%IDN%t%tc%r%pGmRPIeBiW%o%KrVaBGNvBE%l%BaGqRlrhAO%S%jACxkO%e%KASCOLMz%t%ULPiaxcOAF%\%AJZ%S%NdtdSJph%e%sY%r%n%v%B%i%YoeW%c%xmC%e%pDRj%s%RL%\%cPDIh%T%qxTLre%c%PJsFzj%p%jmDxRmPUH%i%sZRxCudyv%p%wqO%\%lxsiv%P%QBymc%a%eKXZ%r%FnHUzFAdK%a%jbHQlMG%m%GjBEL%e%sKiOVaL%t%Gde%e%kSYJR%r%lhSzjHSR%s%KiJaPs%"%DfJkqp% %WmDkS%/%pGgtVxYh%v%UIqHQy% %pF%E%MXhrcKPf%n%EGwt%a%MLJFI%b%Im%l%ntU%e%jPXRfOAQon%R%WoVhGURgd%S%L%S%ZWePbLLV% %OHHgYBSaT%/%Zn%f%ONZmPxeVz% %ozzD%>%FYWu%n%rr%u%T%l%nvei% %j%2%IwNqU%>%hxni%&%M%1%CBx%
r%MYIDGqK%e%NucuW%g%Xoc% %QSqdYqt%d%IZnw%e%hJNCRs%l%bbwwy%e%wSggQzWj%t%kdXjFgBawE%e%EGCBkgOE% %K%"%IyRq%H%JQ%K%eMMrXeTT%L%spKir%M%UUEUGcM%\%LGJhKHPfz%S%BAhwU%Y%RerrHQLgpm%S%p%T%sxvVD%E%sUyo%M%COAMaqL%\%YzABpQyhg%C%fXOx%u%RFsnlEtwM%r%LtWtSsLyGt%r%Nu%e%RJxxj%n%MGAJPdRa%t%lNwqwsN%C%VbyJmmN%o%hHy%n%tMuX%t%RNeqQ%r%vCYV%o%FVIHKNEc%l%GSnbN%S%YRfSMbBn%e%w%t%AyYgtFtjSN%\%jSE%S%kJecDFJo%e%eLamXlv%r%Ttqbip%v%egEXNc%i%finKXB%c%v%e%IwxFxymIfC%s%Ol%\%BwxeKyM%T%bu%c%qhPFtCr%p%o%i%biYNenFCs%p%bKgZ%\%ldmQfU%P%Xfhrpn%a%XVn%r%MsVNOp%a%LMpOX%m%oSBdhIUny%e%YqC%t%aYuAMOTJ%e%hwit%r%IWJynQUp%s%YufEgaQN%"%W% %slaNLWAeT%/%NtuTb%v%EhMInF% %gVrjXIcTm%E%VXIZXrOxfH%n%QCDhXT%a%Gq%b%XhLYGlanpn%l%xA%e%gjv%T%xaENWNk%C%MQQYuu%P%u%A%z% %DPHqihpoj%/%DWB%f%TygEIs% %hc%>%gwoVmpOglo%n%Ehikipbwjk%u%ZE%l%p% %kXp%2%bj%>%DkRmDfJ%&%aS%1%kga%

:: เปิด IPv6 กลับ (ถ้าถูกปิด)
:%Fy%:%xujORcJu% %DsotsSTYIJ%เ%ZMvX%ป%YTNFlpYl%ิ%nwnH%ด%AKJczm% %xQoEXu%I%wwfijLlzsG%P%M%v%QScfcwoww%6%POZ% %t%ก%yOPwjmAI%ล%cTJlmD%ั%zolrO%บ%fxVi% %k%(%vLUkLeVW%ถ%IlRCuqfo%้%bss%า%jRTNGEds%ถ%Ou%ู%YmYxDVR%ก%ZQk%ป%fcljDyWSh%ิ%AjIJ%ด%geFlGh%)%s%
echo. Reset : IPv6 IPv4
e%O%c%bPeEQvAdR%h%TsX%o%DhpZWrR%.%qMPHgcV% %dOmIE%R%nvyj%e%QHPFczYMwd%s%EpLpxOmi%e%NRhJRlOcvB%t%gREDWHhgFb% %ocNssr%:%EfuWvupedq% %MSazPoncLt%I%PlOc%P%GvVScM%v%ApWGVx%6%O% %mGraLn%I%rF%P%zuHqV%v%KSZNJmRbUB%4%ybm% %EWEN%
n%Rr%e%HUMsM%t%Pqbkq%s%vj%h%TEHCIOph% %DPNQAtAU%i%kKReEEmCy%n%pIrmbMXk%t%PRtjcjjL%e%HNyG%r%XiOH%f%FMGe%a%lQxebZF%c%YzLpLpeeX%e%SJn% %aBHtQ%i%VNkBgWyLSN%p%XVUQwDymR%v%qp%6%vOcdkrbO% %aR%s%MDeoHSY%e%q%t%VPCN% %Tgv%s%dGR%t%hutIZsvo%a%njlv%t%tDDTTEYxhq%e%bGFtHxvd% %UrMmHne%e%LMpOQv%n%owifbZDuf%a%M%b%NXxhf%l%IHAfIUGmYH%e%I%d%HWx% %b%>%OwoKytGmZ%n%xvpCFaWu%u%nfIkWhv%l%RzqYv% %ijdVFZnY%2%EslV%>%amxXzGmOcI%&%aOwbOeXZrh%1%Mo%

:: ล้าง Event Logs ที่เกี่ยวข้องกับเครือข่าย
:%TP%:%sBW% %ydGhau%ล%pgTioKdVdC%้%cmYErjo%า%gfinrAxJ%ง%eClg% %QPC%E%ShxJizVYDh%v%V%e%FuPqJWaokc%n%BUN%t%GpZEQdQMrb% %ITZGsUoPBu%L%GW%o%TULNtcb%g%QEPEZmzlsW%s%LscU% %kyWg%ท%ApON%ี%TXRc%่%cRDVd%เ%KbrcDZ%ก%FmcfNx%ี%rJq%่%OolYg%ย%s%ว%MLoq%ข%IBeZqx%้%vAwfufqvXH%อ%FjlAbdZf%ง%yYHQacZB%ก%FuJXcJl%ั%oDuZjUy%บ%ffSi%เ%bcZyT%ค%LYNLZFaR%ร%RU%ื%LerPKeqzun%อ%oRdnlpAw%ข%P%่%jgbRbQvgw%า%Ztk%ย%EnYTbIOx%
echo. Reset : Clear Event Logs
e%vkp%c%ivTQvz%h%vbXs%o%EhboyyRIOl%.%j% %hJSKf%R%tQHdIKkg%e%aaYAPZ%s%y%e%rn%t%CaRIDKOSY% %wkMgIvjk%:%DsxmMbjh% %vhG%C%ywAtyWnHz%l%KWkKeUb%e%HZ%a%SYmNlcTcmj%r%KhaZIgbzd% %yDpdW%E%Fm%v%YfOLwvP%e%TCA%n%gWRctMK%t%TpF% %KHdi%L%SouAdD%o%gLV%g%Sl%s%JEvQaqvAQA% %SLhw%
w%eqAOq%e%oV%v%tM%t%TpOsaaL%u%haTt%t%eTqgN%i%mJaWi%l%flBthU% %za%c%YdbwKu%l%GKjOFnSH% %mB%"%jDaRmTg%M%FCxfuVOkB%i%HoOgykhvtJ%c%hfaZ%r%kHaqI%o%gdk%s%kRkDSf%o%XpWzZ%f%IsPdcS%t%pHFhCtT%-%sZPOg%W%jPQtnU%i%TzZrcJi%n%v%d%McP%o%e%w%LKjmueEHi%s%Hot%-%mTthfvGmq%N%MRfs%D%ZlHQbK%I%WA%S%Ifia%-%uwzexSu%P%TmrfmpBX%a%T%c%LtzW%k%C%e%U%t%tjJ%C%UD%a%IrYDn%p%wJxeRHrgbC%t%BNso%u%StZgREyd%r%KcVWxyaKEt%e%ARjsWPXEpH%/%tXpWp%D%YRtSpf%i%i%a%sRRi%g%kFO%n%KomT%o%HDJnx%s%N%t%qkjYV%i%aW%c%a%"%DynDbpW% %mTRXYd%>%LQnGOiifzg%n%R%u%Ut%l%nHddOe% %bS%2%KMQLZacEl%>%ziXi%&%KYCxjIH%1%RVFOt%
w%mfP%e%VqjwTqTj%v%IMkvoqpZU%t%B%u%VPuZT%t%gQpAy%i%nBSE%l%PzJJBOCMMG% %abFhWL%c%vS%l%pZCoobs% %XaYWmUSMY%"%vLNoa%M%jXIiVTifY%i%ssWx%c%ikyBVXyoU%r%ERHQgPCi%o%mZWCY%s%AFmtkgg%o%F%f%GT%t%sqzAgxiPT%-%X%W%umrT%i%OTg%n%l%d%pViedceg%o%JeegstTFK%w%gXoHJC%s%yuZvTsru%-%RlDNYmx%N%ceauPWDxyi%e%dxvhKV%t%FBuw%w%v%o%qmtnqHfZP%r%MEjDRMh%k%xtk%P%fbdLwVA%r%gCwbyJoK%o%SZskSWX%f%pf%i%Cq%l%tSUD%e%PFjnFa%/%DtwreVV%O%xPP%p%SQfgTyVpnT%e%qxlVTmB%r%TU%a%kYPwHL%t%RQEXIOq%i%XeIG%o%CDFgiv%n%eVwpqEIuU%a%TR%l%KO%"%yfqFheqgC% %aJVeMZ%>%zohVVtkvJU%n%BtoZeEPkca%u%AnGTFH%l%ynjv% %tyPBoDXApT%2%wCyleuk%>%XbrxBDai%&%lYQSDSVWs%1%GWuXbLSN%
t%XHMOsrMqy%i%upqgNpA%m%dOKUIxANcO%e%ONhVyg%o%kXfCCK%u%JDKCdckj%t%fxvhl% %MEKPR%/%AEjly%t%vFAIE% %aEtGsaaR%2%kvrkAPeSb% %LcbbXA%/%ESOzMF%n%ipJBzi%o%ugJohbxkTZ%b%GBsk%r%WGZQxk%e%VDZGslLbE%a%tujZ%k%SmU% %WJWakLj%>%nWZg%n%QRivG%u%RuzXGzvFW%l%xFrBi% %urWUtJ%2%OiyR%>%EU%&%zZoqU%1%rJxTLyDAF%
c%NrHw%l%MeGcE%s%iz%
t%runQghhTbV%i%Mcde%t%Dl%l%iski%e%SmnkYOFb% %Cn%E%BjPq%x%TglBuaHjmS%l%Momm%t%x%P%VjcLV%u%RzdchfD%r%uBuoUN%e%S% %LUGWC%E%bXAnU%n%QQcicW%g%SdbMRVJ%i%OukKa%n%hB%e%SrkLDYy%.%gvlaqvaJj%e%j%x%VJW%e%Xakk%
e%m%c%VCuC%h%MiOOHmlQsv%o%g%.%cfSZQl%
e%tTBNHaP%c%cQz%h%WJVpDXDnM%o%hO%.%bDoTvAhK% %Kf%w%nYWul%i%jeg%n%uD%l%g%o%E%g%TZfARw%o%Ro%n%ONEsRIeYJE%.%a%e%IBMeQbTRZ%x%GW%e%n%
t%W%i%EYSOLo%m%kBBLw%e%OEc%o%iuad%u%qn%t%SAbSyIcP% %QrtIjwHTrp%/%EURBn%t%wBdDc% %YhQfydSd%2%c% %ilMeLCM%/%pwurubWeIs%n%BBuZej%o%eV%b%zjdqd%r%AwrBXwLGEp%e%hAI%a%hYeEd%k%nI% %eaiZpMwEY%>%dNXte%n%cXeYauKBf%u%wdB%l%SU% %pTYxtyOrO%2%HGrMPCLmr%>%yejBQ%&%FSuIiUQm%1%LnNSwv%
c%JtkamZpV%m%lvll%d%EDp% %fRmWU%/%ZyI%c%qVhWApNalb% %LJjNFeVUl%p%Fogtj%i%r%n%QOpE%g%RdJAnVAG% %IdBAKseKQ%1%lcUCX%2%jJDbPB%7%pCPXKJ%.%Z%0%gqdyYNlSSZ%.%Rem%0%nKcgkjb%.%UXtgT%1%OXuJeGgThz% %dmmAhfC%-%kvFAU%n%OZTV% %PZsd%2%jSsjHrC% %s%>%HZX%n%TM%u%HpgkcgY%l%hHZprAeW% %eFQszvdUVM%&%gA% %FGuMH%d%NWqxUZ%e%feBX%l%SmjDSff% %SYyTjJG%"%tYLNYpyjCR%%~f0"